from django import forms
from django.forms import ModelForm


SUBONT_CHOICES = [
	('', '-------'),
	('Indirect biological role', 'Indirect biological role'),
	('Industrial process', 'Industrial process'),
	('Industrial application', 'Industrial application'),
]

SUBONT1_TERM_CHOICES = [
	('', '-------'),
	('Acnegenic', 'Acnegenic'),
	('Allergen', 'Allergen'),
	('Amnesigenic', 'Amnesigenic'),
	('Cardiotoxin', 'Cardiotoxin'),
	('Cerebrotoxic', 'Cerebrotoxic'),
	('Cyanotoxin', 'Cyanotoxin'),
	('Embryotoxic', 'Embryotoxic'),
	('Endocrine_disrupting', 'Endocrine_disrupting'),
	('Enterotoxic', 'Enterotoxic'),
	('Genotoxin', 'Genotoxin'),
	('Hepatomegalic', 'Hepatomegalic'),
	('Hepatotoxin', 'Hepatotoxin'),
	('Lupus_generating', 'Lupus_generating'),
	('Marine_biotoxin', 'Marine_biotoxin'),
	('Mycotoxin', 'Mycotoxin'),
	('Nephrotoxin', 'Nephrotoxin'),
	('Neurotoxin', 'Neurotoxin'),
	('Pancreatoxic', 'Pancreatoxic'),
	('Phytotoxin', 'Phytotoxin'),
	('Poison', 'Poison'),
	('Pulmonotoxic', 'Pulmonotoxic'),
	('Reprotoxic', 'Reprotoxic'),
	('Respirotoxic', 'Respirotoxic'),
	('Toxin', 'Toxin'),
	('Uremic_toxin', 'Uremic_toxin'),
	('Venom', 'Venom'),
	('Xenobiotic', 'Xenobiotic'),
	('Carcinogen', 'Carcinogen'),
	('Cytotoxin', 'Cytotoxin'),
	('Mutagen', 'Mutagen'),
	('Teratogen', 'Teratogen'),
	('Osteotoxin', 'Osteotoxin'),
	('Renal_toxin', 'Renal_toxin'),
	('Immunotoxin', 'Immunotoxin'),
	('Metabotoxin', 'Metabotoxin'),
	('Acidogen', 'Acidogen'),
	('Diabetogen', 'Diabetogen'),
	('Atherogen', 'Atherogen'),
	('Mitochondrial_toxin', 'Mitochondrial_toxin'),
	('Arthritogen', 'Arthritogen'),
	('Phototoxin', 'Phototoxi'),
]

SUBONT2_TERM_CHOICES = [
	('', '-------'),
	('Leaching', 'Leaching'),
	('Metallurgical_process', 'Metallurgical_process'),
	('Petroleum_processing', 'Petroleum_processing'),
	('Chelation', 'Chelation'),
	('Desalination', 'Desalination'),
	('Desalination', 'Desalination'),
	('Water_purification', 'Water_purification'),
	('Water_disinfection', 'Water_disinfection'),
	('Ammonia_production', 'Ammonia_production'),
	('Distillation', 'Distillation'),
	('Reverse_Osmosis', 'Reverse_Osmosis'),
	('Sedimentation', 'Sedimentation'),
	('Filtration', 'Filtration'),
	('Disinfection', 'Disinfection'),
	('Chlorine_dioxide_disinfection', 'Chlorine_dioxide_disinfection'),
	('Chloramine_disinfection', 'Chloramine_disinfection'),
	('Ozone_disinfection', 'Ozone_disinfection'),
	('Ultraviolet_disinfection', 'Ultraviolet_disinfection'),
	('Gamma_radiation', 'Gamma_radiation'),
	('Water_fluoridation', 'Water_fluoridation'),
	('Water_conditioning', 'Water_conditioning'),
	('Bioremediation', 'Bioremediation'),
	('Fermentation', 'Fermentation'),
	('Combustion', 'Combustion'),
]

SUBONT3_TERM_CHOICES = [
	('', '-------'),
	('Algicide', 'Algicide'),
	('Nematicide', 'Nematicide'),
	('Feed_Additive', 'Feed_Additive'),
	('Fertiliser', 'Fertiliser'),
	('Insect_Attractant', 'Insect_Attractant'),
	('Insect_Attractant', 'Insect_Attractant'),
	('Plant_growth_regulator', 'Plant_growth_regulator'),
	('Ripening_agent', 'Ripening_agent'),
	('Fertilizer', 'Fertilizer'),
	('Herbicide', 'Herbicide'),
	('Insect_repellent', 'Insect_repellent'),
	('Insecticide', 'Insecticide'),
	('Acaricide', 'Acaricide'),
	('Ant_Repellent', 'Ant_Repellent'),
	('Aphidicide', 'Aphidicide'),
	('Animal_Repellent', 'Animal_Repellent'),
	('Biocide', 'Biocide'),
	('Horticultural_Spray_Oil', 'Horticultural_Spray_Oil'),
	('Pesticides', 'Pesticides'),
	('Fumigant', 'Fumigant'),
	('Adhesive', 'Adhesive'),
	('Flame_retardant', 'Flame_retardant'),
	('Acidulant', 'Acidulant'),
	('Flavor_Enhancer', 'Flavor_Enhancer'),
	('Foam_Stabilizer', 'Foam_Stabilizer'),
	('Acidity_Regulator', 'Acidity_Regulator'),
	('Baking_agent', 'Baking_agent'),
	('Color_Retention_Agent', 'Color_Retention_Agent'),
	('Firming_Agent', 'Firming_Agent'),
	('Flavor_Solvent', 'Flavor_Solvent'),
	('Flavoring_Agent', 'Flavoring_Agent'),
	('Food_additive', 'Food_additive'),
	('Food_color', 'Food_color'),
	('Food_preservative', 'Food_preservative'),
	('Improving_Agent', 'Improving_Agent'),
	('Nutritional_supplement', 'Nutritional_supplement'),
	('Packaging_Gas', 'Packaging_Gas'),
	('Raising_agent', 'Raising_agent'),
	('Resolving_Agent', 'Resolving_Agent'),
	('Seasoning', 'Seasoning'),
	('Sweetener', 'Sweetener'),
	('Thickening_Agent', 'Thickening_Agent'),
	('Sequestrant', 'Sequestrant'),
	('Fragrance_Component', 'Fragrance_Component'),
	('Glazing_Agent', 'Glazing_Agent'),
	('Anticaking_agent', 'Anticaking_agent'),
	('electrolyte_replenisher', 'electrolyte_replenisher'),
	('enzyme_replacement_agent', 'enzyme_replacement_agent'),
	('Prebiotic', 'Prebiotic'),
	('Deodorant', 'Deodorant'),
	('Hair_conditioner', 'Hair_conditioner'),
	('UV_filter', 'UV_filter'),
	('Anti_AIDS', 'Anti_AIDS'),
	('Antiadenoviral', 'Antiadenoviral'),
	('Antiflu_agent', 'Antiflu_agent'),
	('Antipapillomic', 'Antipapillomic'),
	('Antipoliomyelitic', 'Antipoliomyelitic'),
	('Antirabies', 'Antirabies'),
	('Antiretroviral', 'Antiretroviral'),
	('Antirhinoviral', 'Antirhinoviral'),
	('Antivaccinia', 'Antivaccinia'),
	('Ascaricide', 'Ascaricide'),
	('Vermifuge', 'Vermifuge'),
	('Anticytomegalovirus', 'Anticytomegalovirus'),
	('AntiEpstein-Barr_virus', 'AntiEpstein-Barr_virus'),
	('Anticancer_agent', 'Anticancer_agent'),
	('Anticarcinogenic', 'Anticarcinogenic'),
	('Anticarcinomic', 'Anticarcinomic'),
	('Antihepatocarcinogenic', 'Antihepatocarcinogenic'),
	('Antileukemic', 'Antileukemic'),
	('Antimelanogenic', 'Antimelanogenic'),
	('Antimelanomic', 'Antimelanomic'),
	('Antimetastatic', 'Antimetastatic'),
	('Antineoplastic', 'Antineoplastic'),
	('Antitumor', 'Antitumor'),
	('Antitumor_promoter', 'Antitumor_promoter'),
	('Cancer_preventive', 'Cancer_preventive'),
	('Carcinostatic', 'Carcinostatic'),
	('chemopreventive', 'chemopreventive'),
	('Antiarrythmic', 'Antiarrythmic'),
	('Antiatherogenic', 'Antiatherogenic'),
	('Antiatherosclerotic', 'Antiatherosclerotic'),
]

KLASS_CHOICES = [
	('', '-------'),
	('Hybrid glycopeptides', 'Hybrid glycopeptides'),
	('Hybrid peptides', 'Hybrid peptides'),
	('Miscellaneous arsenites', 'Miscellaneous arsenites'),
	('Triazinones', 'Triazinones'),
	('Organobromides', 'Organobromides'),
	('Alpha amino acids and derivatives', 'Alpha amino acids and derivatives'),
	('Podophyllotoxins', 'Podophyllotoxins'),
	('Retinoids', 'Retinoids'),
	('8-methoxypsoralens', '8-methoxypsoralens'),
	('Nitrogen mustard compounds', 'Nitrogen mustard compounds'),
	('Dicarboxylic acids and derivatives', 'Dicarboxylic acids and derivatives'),
	('Nitrogen mustard compounds', 'Nitrogen mustard compounds'),
]

class SearchForm(forms.Form):
	mw_from = forms.FloatField()
	mw_to = forms.FloatField()
	logp_from = forms.FloatField()
	logp_to = forms.FloatField()
	subont1 = forms.CharField(widget=forms.Select(choices=SUBONT_CHOICES))
	subont2 = forms.CharField(widget=forms.Select(choices=SUBONT_CHOICES))
	subont3 = forms.CharField(widget=forms.Select(choices=SUBONT_CHOICES))
	term1 = forms.CharField(widget=forms.Select(choices=SUBONT1_TERM_CHOICES))
	term2 = forms.CharField(widget=forms.Select(choices=SUBONT2_TERM_CHOICES))
	term3 = forms.CharField(widget=forms.Select(choices=SUBONT3_TERM_CHOICES))
	klass = forms.CharField(widget=forms.Select(choices=KLASS_CHOICES))

class ResultsForm(forms.Form):
	here = ""